### ISSUE TITLE
"Unsubmit" talk seems to delete the conference

### ISSUE THREAD

**Issue by greydnls** [tightenco/symposium#104]
Working locally, I created a conference, created a talk. I marked that talk as "submitted" to my test conference. 

Once I clicked "unsubmit", the conference gets deleted as well.

**Comment by mattstauffer** [comment]
Tried to reproduce; added a test here: 
https://github.com/tightenco/symposium/pull/105/files#diff-7d2dcd5e3ea1984abc236f9c03692367R46
(not merged yet, but is green when I run it right now.)

Can you reproduce it?

**Comment by mattstauffer** [comment]
Closing because can't reproduce.
