### ISSUE TITLE
The "something happened successfully" alerts are annoying :)

### ISSUE THREAD

**Issue by adamwathan** [tightenco/symposium#107]
They cover up parts of the page and can't be manually dismissed, and take a while to dismiss automatically.

Few ideas:
1. Move them somewhere else, like bottom-right-corner-of-the-eye sort of deal and make them less attention grabby color wise? So it's there, but it's not screaming for your attention vs. the rest of the page.
2. Think of ways to avoid them when possible, instead of "use them by default" approach. Lots of screens that use them (create bio for instance) redirect to the page that shows you what you just created anyways, so it's already clear that it was saved.

**Comment by mattstauffer** [comment]
agreed :+1:

**Comment by rdohms** [comment]
I think having positive feedback even, or espcially if we redirect back is a good UX, users like the "feel good" feeling of "stuff was good". I do agree with making them a popover in the lower right kinda thing approach.

**Comment by adamwathan** [comment]
One clear example I think could go, "Successfully logged in!" :)

**Comment by jwalton512** [comment]
An additional note, some of the alerts persist if a user navigates to another page and then hits back on the browser.

**Comment by mattstauffer** [comment]
Not enough, but temporary fix ^^

**Comment by Xethron** [comment]
#197 tries to fix this by moving it to the top right. I tried the bottom right, but it looks odd, especially on pages where there isn't a lot of content (Having a single bio, or a single talk).

I haven't changed the colour at all, however, having it smaller and to the right, really removes the "screaming" effect.

Opinions welcome :)
