### ISSUE TITLE
Strengthen the relation between pronto and symposium

### ISSUE THREAD

**Issue by rdohms** [tightenco/symposium#111]
I would really like to get more traction going between both projects.

In 0.4 i added a bunch of links leading back to symposium for "add new talks" and links to see/edit current talks back in symposium.

I would love to hear if you guys have any ideas on how to promote it from the symposium side, if you ar willing to do it.

BTW: My roadmap also includes expanding to other browsers, slowly.

**Comment by mattstauffer** [comment]
I'm 100% down with that. Feel free to PR anything or I'll take a look at some good places next week when I'm back in the office 

Sent from Outlook




On Fri, Aug 28, 2015 at 2:16 PM -0700, "Rafael Dohms" <notifications@github.com> wrote:












I would really like to get more traction going between both projects.



In 0.4 i added a bunch of links leading back to symposium for "add new talks" and links to see/edit current talks back in symposium.



I would love to hear if you guys have any ideas on how to promote it from the symposium side, if you ar willing to do it.



BTW: My roadmap also includes expanding to other browsers, slowly.

**Comment by mattstauffer** [comment]
![image](https://cloud.githubusercontent.com/assets/151829/15805609/c54efd92-2afd-11e6-95b4-703f8f665272.png)

![image](https://cloud.githubusercontent.com/assets/151829/15805610/c87d52f2-2afd-11e6-8e19-e4df8017736d.png)

Done!

**Comment by rdohms** [comment]
W00t!
