### ISSUE TITLE
Allow uploading profile photo

### ISSUE THREAD

**Issue by adamwathan** [tightenco/symposium#116]
A lot of CFPs (OpenCFP for example) asks for a profile photo when submitting talks.

It would be nice to be able to grab it from Symposium instead of Twitter or LinkedIn or whatever when submitting to a conference, so that everything you need for a submission is all in one place.

**Comment by mattstauffer** [comment]
Agreed! This is captured in an earlier issue but we can just close the earlier one (will try to find it later to close)

**Comment by mattstauffer** [comment]
Duplicate was #2. Second issue ever, probably time we get around to it. :) Closing #2 because there's more explanation/context in this one.
