### ISSUE TITLE
Add slides URL to talk profile

### ISSUE THREAD

**Issue by asgrim** [tightenco/symposium#122]
Feature request: OpenCFP (the most common platform for entering data) has a "Slides URL" field, and when used with https://github.com/rdohms/pronto, it would be great if Pronto could grab that field from Symposium and pop it into OpenCFP :)

**Comment by mattstauffer** [comment]
:+1:

**Comment by mattstauffer** [comment]
Interesting idea, though: You may want a different version of the slides depending on which submission you're sending, right? So... that may depend on us expanding the distinction between a talk ("Object-Oriented CSS") and a submission ("Object-Oriented CSS at Sunshine PHP"). Think we're doing this in #99, so this may depend on #99.

**Comment by rdohms** [comment]
Actually, this would be the "sample slides" .. not used by many people. I would say if we had something like "adding slides to a talk" like we discussed the rating stuff.. then you may click on one and say "use as submission slide".. know what i mean?

**Comment by mattstauffer** [comment]
Yah, agreed.

**Comment by asgrim** [comment]
yay! Thanks :)
