### ISSUE TITLE
SSL Cert needs to be purchased and added

### ISSUE THREAD

**Issue by shadowhand** [tightenco/symposium#124]
Both register and login should only be happening through HTTPS connections. The default Symposium app at http://symposiumapp.com/ not only doesn't redirect to HTTPS by default, it has a broken SSL certificate when you change the URL manually.

This is not good for security or peace of mind.

**Comment by elazar** [comment]
May be useful in resolving this: https://letsencrypt.org

**Comment by mattstauffer** [comment]
Known concern, thanks for adding as issue. 👍

**Comment by mattstauffer** [comment]
FYI, letsencrypt out of beta nov 16, will use that.

**Comment by elazar** [comment]
If you run into any issues, @svpernova09 may be willing to assist. He recently added SSL support using LetsEncrypt on phergie.org.
