### ISSUE TITLE
Idea - "archive" talks

### ISSUE THREAD

**Issue by asgrim** [tightenco/symposium#126]
It'd be cool if I could "archive" a talk, so it doesn't normally appear (and doesn't appear in Pronto @rdohms), but I can still go back to it and re-activate it or something (so I still have a record of it, instead of hard-deleting it)

**Comment by greydnls** [comment]
With the merging of #179 this issue is resolved, correct?

**Comment by besologic** [comment]
👍

**Comment by asgrim** [comment]
Awesome! Thanks folks :)
