### ISSUE TITLE
Improve public pages

### ISSUE THREAD

**Issue by rdohms** [tightenco/symposium#127]
Practically the whole website is locked behind login, maybe we could start opening up a few pages? Off the top of my head the conference page is a good one to open up.

With the profile stuff coming along then maybe we should give the front page more life with some stats and lists?

Could also make the front page more like the pronto page i cooked up, list some stats, show the benefits, like being able to use pronto and etc...

**Comment by mattstauffer** [comment]
@rdohms BTW, I couldn't agree with this more. <3

**Comment by Xethron** [comment]
Ok, so Conferences are now open. As for stats, you thinking like number of:
 - Speakers Registered
 - Talks created
 - Talk Reversions
 - Conferences
 - Submissions to conferences

That kinda stats?

Perhaps also: Average number of talk submissions per speaker to conferences, average number of active talks per speaker... Those could be interesting.

(Ok, I've lost it again) And maybe, list the speaker with the most public talks, as well as the talk with the most reversions :D

I'll stop there :)

**Comment by mattstauffer** [comment]
Closing until we get more concrete proposals for public pages. Thanks for suggestions and PRs!
