### ISSUE TITLE
Allow sorting on the `Talks` endpoint of the API

### ISSUE THREAD

**Issue by rdohms** [tightenco/symposium#128]
As per rdohms/pronto#28 it would be nice to get the sorted talks directly from the API.

If you think this is not the place for sorting i can proceed to implement it locally, no problem.

**Comment by rdohms** [comment]
@mattstauffer any idea on this?

**Comment by mattstauffer** [comment]
@rdohms I'd love to get to it. Let's make a trade: if you take a look at #160, I'll make this my first priority once I update to 5.2 :D thanks for following up on this, apologies for the delay!

**Comment by mattstauffer** [comment]
"take a look at" = read this comment https://github.com/tightenco/symposium/pull/160#issuecomment-223095684

**Comment by rdohms** [comment]
I'll see what i can do :P was just checking if its something you are willing to put on the roadmap

**Comment by mattstauffer** [comment]
Done!
