### ISSUE TITLE
User accounts don't need distinct first and last names

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/symposium#130]

**Comment by jwalton512** [comment]
@mattstauffer sounds like you are wanting to move away from have `first_name` and `last_name` and instead just have `name`.

from an outside contributor perspective, how would you prefer this be submitted?

pretty simple to send through the migration/model/view updates adding `name`, but somewhere in production the actual altering of the data would need to be done.  then at some point, subsequent migrations to drop the old fields would be needed.

**Comment by mattstauffer** [comment]
@jwalton512 That's exactly it.

I think my favorite option is to write the data updating right into the migration, and then we delete that part of it in a later PR.

Pseudo code:

class 204910249120481204_merge_first_and_last_name
   up
        add name field

       users->all(function(user)
            this->name = this->first_name . ' ' . $this->last_name; this->save
          
       drop first_name and last_name field


then in a later PR we can just delete the users->all code and merge it into one normal migration

**Comment by jwalton512** [comment]
@mattstauffer works for me, i should be able to submit something.  do you have a db backup? 😛

**Comment by mattstauffer** [comment]
@jwalton512 Haha, yep, got a daily backup on [Ottomatik](https://ottomatik.io/?refcode=kjQb2QlB):

![image](https://cloud.githubusercontent.com/assets/151829/11251374/f0323dfe-8dfe-11e5-983a-5089fbc613e0.png)
