### ISSUE TITLE
Fixing «cURL error 3: <url> malformed»

### ISSUE THREAD

**Issue by atefBB** [tightenco/symposium#152]
Hi Matt, There's a prob with the signing-up, when a user try to sign-up The following error appeared: «cURL error 3: <url> malformed», it's about Guzzle requests ! how did you fix it? 
Thanks. 
(it's my first issue so be tolerant about my english and my ignorance)

**Comment by mattstauffer** [comment]
@atefBB Not sure, I've never seen it before. Could you get any more information about the error? A stack trace or a screenshot or anything? Can you show me which page and what you entered into each field? Thanks!

**Comment by atefBB** [comment]
Sure ‼ when I try to sign-in this error appeared.
![err](https://cloud.githubusercontent.com/assets/10966925/12049320/ff0e3ee2-aee5-11e5-8f01-cc766bfb57bd.png)

**Comment by mattstauffer** [comment]
Ah, that's an improperly configured Slack endpoint. Do you have the latest code? I thought that had been fixed recently.

**Comment by atefBB** [comment]
how to fix it? plz ‼

**Comment by mattstauffer** [comment]
This fix should've fixed it: https://github.com/tightenco/symposium/pull/132

So your first step is to make sure you have the latest code. If you have the latest code, then please let me know here and I will attempt to dig into the problem when i have time

**Comment by andreasbaumann** [comment]
In libcurl lib/url.c: 

```
rc = sscanf(data->change.url, "%[^\n/?#]%[^\n]", conn->host.name, path);

failf(data, "<url> malformed");
          return CURLE_URL_MALFORMAT;
```
Most likely it doesn't like the :443, as this is implicitely the default port of https.
