### ISSUE TITLE
Default Profile Photo

### ISSUE THREAD

**Issue by atefBB** [tightenco/symposium#153]
If user try to sign-up in the site and he hasn't a photo on Gravatar, it's should appear for him a default profile photo. I do this:
![grav-test](https://cloud.githubusercontent.com/assets/10966925/12064380/0bb6f026-afc2-11e5-9f8f-20987108ccae.png)

have you an idea?

**Comment by mattstauffer** [comment]
Gravatar gives you a default photo if it can't find your email address.

![image](https://cloud.githubusercontent.com/assets/151829/12065978/641befd2-afae-11e5-8d12-2e7d5093d06f.png)
