### ISSUE TITLE
Conferences resource permissions

### ISSUE THREAD

**Issue by edupacios** [tightenco/symposium#158]
I'm sorry if I'm missing something. I just want to understand to help. The conferences controller is under auth middleware in routes, but in the controller's constructor there's a 'beforeFilter' which is limited to create, store, edit, update and destroy, and doesn't seem to work. I couldn't find it's declaration (no filters.php, nothing in RouteServiceProvider, maybe it comes from the first versions of the app in Laravel 4)

The index method shows all conferences (no matter the author), but when the user clicks on one it fails if he doesn't own it: 
```
$conference = Auth::user()->conferences()->findOrFail($id);
```
This line fixes it, but I want to be sure of what's the intended logic to make modifications:
```
$conference = Conference::findOrFail($id);
```
This method also checks if user is not logged in to show a public version of the conference, but a guest won't reach that point as there's the auth and an oauth beforeFilter.

**Comment by mattstauffer** [comment]
Thanks @edupacios and @patkar
