### ISSUE TITLE
Link to conferences throws a 404

### ISSUE THREAD

**Issue by patkar** [tightenco/symposium#163]
The link to a conference e.g. http://symposiumapp.com/conferences/3de13906-ccc6-4ca8-bb65-40230ff1e91c throws a 404 "Sorry, the page you are looking for could not be found." error :(

**Comment by mattstauffer** [comment]
Can't reproduce--even that example link works. Must've been fixed since?

**Comment by patkar** [comment]
Happens only when logged in.

**Comment by mattstauffer** [comment]
Aha, can reproduce--404s if you're logged in and don't own it. Duplicate #158
