### ISSUE TITLE
Re-enable CSRF protection

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/symposium#169]
It was seemingly disabled back when it was a bit of a pain during its first transition to a middleware. Now let's bring it back.

**Comment by michaelrtm** [comment]
Starting this now. Are all forms covered by the current tests?

**Comment by michaelrtm** [comment]
Ok, so I've uncommented `\App\Http\Middleware\VerifyCsrfToken::class,` and run the tests, and everything is green (except one test, but it is yellow regardless of my change).

It seems that the form builder automatically throws the token in... am I missing something, or was it that simple?

**Comment by mattstauffer** [comment]
@michaelrtm I always hoped this would be an easy transition. However, I don't know that I can say all forms are covered by tests. I *want* them to be, so we could do a manual walkthrough of all the forms, find which don't have tests, fix them for CSRF, and make other issues for the tests.

**Comment by michaelrtm** [comment]
I've looked through the resources and tests and found a bunch of missing tests - starting to write them now.

Do you want me to move existing tests around, or leave them as is? 

For example I'm doing Bio CRUD now in a new test called `BioTest` and found `bios_marked_not_public_do_not_have_public_pages()` in `PublicSpeakerProfileTest`.

**Comment by mattstauffer** [comment]
@michaelrtm I think it makes sense in either context--it's both about the bio crud and about the public speaker profile. So no need to move it.
 
Thanks!

**Comment by michaelrtm** [comment]
@mattstauffer this PR can be closed :)

**Comment by mattstauffer** [comment]
Woo thanks @michaelrtm!
