### ISSUE TITLE
Able to create a conference with an 'ends_at' before 'starts_at'

### ISSUE THREAD

**Issue by bmitch** [tightenco/symposium#170]
I was able to create a conference that had an ending date before the starting date.

As well the `cpf_ends_at` date can be before the `cpf_starts_at` field.

I can put together a PR for this but was curious about the rules in the `CreateConferenceForm`.

It has each validation rule as an array and if I try something like this:

```
        'ends_at' => ['date|after:starts_at'],
```
I get a:
```
BadMethodCallException" matches expected exception "Symposium\Exceptions\ValidationException". Message was: "Method [validateDate|after] does not exist.
```

However this works just fine:
```
        'ends_at' => 'date|after:starts_at',
```

Was there a reason for each rule value being an array like that? Maybe I am missing something obvious? :confused:

**Comment by mattstauffer** [comment]
Hey Bill,
If you want to add multiple rules to an array-based rule system, add more
items to the array. So the example you’re giving would be:

‘ends_at’ => [‘date’, ‘after:starts_at’]

Thanks! And that PR would be great!

-matt

On Wed, Jun 1, 2016 at 7:37 PM, Bill Mitchell <notifications@github.com>
wrote:

> I was able to create a conference that had an ending date before the
> starting date.
>
> As well the cpf_ends_at date can be before the cpf_starts_at field.
>
> I can put together a PR for this but was curious about the rules in the
> CreateConferenceForm.
>
> It has each validation rule as an array and if I try something like this:
>
>         'ends_at' => ['date|after:starts_at'],
>
> I get a:
>
> BadMethodCallException" matches expected exception "Symposium\Exceptions\ValidationException". Message was: "Method [validateDate|after] does not exist.
>
> However this works just fine:
>
>         'ends_at' => 'date|after:starts_at',
>
> Was there a reason for each rule value being an array like that? Maybe I
> am missing something obvious? 😕
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tightenco/symposium/issues/170>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAJRFR85FLfuizNXmcdCgn8_cwlUaqn6ks5qHhfQgaJpZM4IsFCp>
> .
>



-- 

*Matt Stauffer*
*Partner + Technical Director*
Tighten Co.
352-682-2765

**Comment by bmitch** [comment]
Oh right of course. Knew it was something obvious :)
