### ISSUE TITLE
Reset Password Link not working

### ISSUE THREAD

**Issue by kkoppenhaver** [tightenco/symposium#174]
@mattstauffer You may have already identified this, but the reset password form at https://symposiumapp.com/password/email returns a 'Whoops, something went wrong.' when the form is submitted.

**Comment by mattstauffer** [comment]
@kkoppenhaver Nope, wasn't aware of it. Thanks!

**Comment by kkoppenhaver** [comment]
Thanks for the quick close! Working now.
