### ISSUE TITLE
Don't require talk length

### ISSUE THREAD

**Issue by michaelcullum** [tightenco/symposium#183]
Some talks work for 40/50/60 minutes (and therefore just submit them to conferences who will then have their own talk slot times) and setting a talk length should be optional, not required.

**Comment by mattstauffer** [comment]
I'm open to the idea. We'd have to figure out how it affects Pronto and the API, but I'm up for it. @rdohms do you know if it would break anything?

**Comment by Xethron** [comment]
I like this idea as it ties in well with #113, having talk lengths defined by talk type. The only type that might not fit is "Keynote", as I've seen both short and long keynotes.

Leaving this as optional/unset might indicate that your talk could possibly fit into any feasible time slot (You'll be able to make it fit) on your public profile.

@rdohms any feedback?

**Comment by rdohms** [comment]
This is fine, if it's blank then pronto just won't fill in the field for time.

**Comment by Xethron** [comment]
Sweet. I think we should close this one and merge it into #113, and continue the discussion there.

**Comment by mattstauffer** [comment]
Agreed @Xethron, Think it's time to handle #113.
