### ISSUE TITLE
CSS for buttons on the show talk page messes up the flow with long titles

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/symposium#198]
![image](https://cloud.githubusercontent.com/assets/151829/19931375/a246ffb0-a0e2-11e6-907f-e64c1fa84f2a.png)

**Comment by Xethron** [comment]
Ok, changing `.page-title` to display block will change the layout on some pages, and there are only 3 places where user input is allowed in a `.page-title`. Two for talk title, and one for bio->nickname.

Option 1: create a class `.page-title-block` and use it in these three places
Option 2: create a class `.block` and override the display to block
Option 3: create a class `.page-title-inline` and change it everywhere else

I like Option 1...

**Comment by mattstauffer** [comment]
I'd prefer a global solution that makes this work the way that's expected without having to differntiate based on user input or not. I feel like if i have some time to throw my CSS brain at it I'l find it but just haven't found that time yet.
