### ISSUE TITLE
Add a calendar

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/symposium#203]
For speakers who spend a lot of their year speaking, it'd be nice to have a calendar of important dates.

As a side idea, we may want to track information that's a little more flexible--when do I need to book my flights by? Reminder to get reimbursed! Almost like an arbitrary calendaring system.. but careful that we don't want to get too far down that road.. not exactly sure how we should do that TBH. 

But we can at least start with a calendar of known events. Probably "CFP close/open for conferences I have favorited" and "conference start/end dates for conferences I have favorited" and "conference start/end dates for conferences I'm accepted to speak at."

**Comment by imjohnbon** [comment]
I started working on this a bit today. Still needs a lot of style cleanup, but I do have a calendar with *all* Conferences being output to it:

<img width="1008" alt="screen shot 2017-06-20 at 6 35 41 pm" src="https://user-images.githubusercontent.com/1489975/27358994-4c13f070-55e7-11e7-9b41-c19d4b895a59.png">

Currently just trying to figure out what we might want to filter the calendar down to. "Favorited" conferences was mentioned in the original message here, but it's possible that "favorites" could be going away per [this PR](https://github.com/tightenco/symposium/pull/215).

If that PR does get merged, I'm not exactly sure what else we could filter by. Except maybe "conferences I'm accepted to speak at", but I'm not sure where the "accepted talks" functionality stands either. I could work on that too if need be.

**Comment by mattstauffer** [comment]
@imjohnbon I think you're right--"all conferences I have not dismissed" is a good start.

Then from there, probably "conferences I'm accepted to speak at."

We could also put CFPs in there in a different color.
