### ISSUE TITLE
Login with Twitter

### ISSUE THREAD

**Issue by rossjcooper** [tightenco/symposium#207]
After briefly reading the issue #56 and seeing the argument about possibly alienating non-techies with a GitHub login, why not use a Twitter login feature in addition to the existing standard signup?

I would imagine the majority of speakers regardless of topic will have a twitter profile as opposed to a GitHub account?

(Thoughts @mattstauffer  and @adamwathan?)

**Comment by mattstauffer** [comment]
Honestly, we only have any ins at all in the tech space right now. That hasn't changed in the last year and a half. I think this is a good idea, but I think I would prefer we start with Adam's original idea:

https://github.com/tightenco/symposium/issues/56#issuecomment-101016944

And then we can add Twitter later if it comes up. So this isn't "no"! But more "I think the proposed solution to mix github and email is the best given our current userbase."

Closing for now. Thanks Ross!
