### ISSUE TITLE
oauth2-server-laravel and guzzle abandoned

### ISSUE THREAD

**Issue by michaelrtm** [tightenco/symposium#216]
```
Package lucadegasperi/oauth2-server-laravel is abandoned, you should avoid using it. Use laravel/passport instead.
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
```
Not sure if there is much of a code change requirement for these, or if this has already been documented somewhere.

**Comment by tomdiggle** [comment]
Would Laravel Passport be a suitable replacement for lucadegasperi/oauth2-server-laravel?

**Comment by mattstauffer** [comment]
@tomdiggle likely, yes

**Comment by tomdiggle** [comment]
If you want, I'd be happy to submit a PR with tests replacing lucadegasperi/oauth2-server-laravel with Laravel Passport.

**Comment by mattstauffer** [comment]
@tomdiggle that would be awesome!
