### ISSUE TITLE
Email Matt every time someone signs up because that's exciting!

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/symposium#22]

**Comment by mattstauffer** [comment]
This issue was moved to tightenco/symposium#22

**Comment by assertchris** [comment]
Has this already been completed? I see that there are Mailgun placeholders, in `.env.example`, and there is code to sent the emails, in `AccountController` but this issue is still open...

**Comment by mattstauffer** [comment]
has been completed. Stupid automated system re-opened it
