### ISSUE TITLE
Redesign from @sschoger <3

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/symposium#228]
![image](https://user-images.githubusercontent.com/151829/31020401-e2485cc6-a500-11e7-9070-1e8929bb116a.png)

![image](https://user-images.githubusercontent.com/151829/31020404-e61d780e-a500-11e7-8ac6-ffebb0de95e0.png)

**Comment by joshrainwater** [comment]
I assume this one is waiting for Tailwind.css, makes the most sense to me.

**Comment by m1guelpf** [comment]
❤️

**Comment by mattstauffer** [comment]
Closing temporarily because @nolveraa is going to be updating and expanding on these designs.
