### ISSUE TITLE
Replace laracasts/TestDummy with Laravel Factories

### ISSUE THREAD

**Issue by tomdiggle** [tightenco/symposium#230]
Laravel 5 now includes its own way to prepare factories which makes this package no longer required. I'll be happy to update the tests, remove this package and submit a PR.

**Comment by tomdiggle** [comment]
@mattstauffer would you it be easier for you if I submitted the changes to PR #229? or created a new PR?

**Comment by mattstauffer** [comment]
@tomdiggle great question. I feel like we should separate it.

**Comment by tomdiggle** [comment]
Ok, I'll submit a separate PR.
