### ISSUE TITLE
Track location on conferences

### ISSUE THREAD

**Issue by greydnls** [tightenco/symposium#244]
It looks like currently we track dates, but no location. I think that's very helpful for speakers to know about, prior to submitting.

**Comment by mattstauffer** [comment]
Geez, yes. City state country post code latitude longitude probably?

**Comment by greydnls** [comment]
I think city state, post code, country is a good start. Lat/long would need to involve an external api of some sort. That could be a fast follow but MVP could be just the above.

**Comment by mattstauffer** [comment]
Yep totes

**Comment by cookieguru** [comment]
@greydnls See #261
