### ISSUE TITLE
Server Error during some artisan joindin:sync calls

### ISSUE THREAD

**Issue by josecanhelp** [tightenco/symposium#255]
## Error in SaveMyProposals

**Guzzle\Http\Exception\ServerErrorResponseException** in **artisan joindin:sync**
Server error response
[status code] 503
[reason phrase] Service Temporarily Unavailable
[url] http://api.joind.in/v2.1/events

[View on Bugsnag](https://app.bugsnag.com/markedstyle/savemyproposals/errors/5c9103f44dee67001ae1908f?event_id=5c9112050037ad33c1770000&i=gh&m=ci)

## Stacktrace

    Console/Commands/SyncJoindInEvents.php:33 - App\Console\Commands\SyncJoindInEvents::fire

[View full stacktrace](https://app.bugsnag.com/markedstyle/savemyproposals/errors/5c9103f44dee67001ae1908f?event_id=5c9112050037ad33c1770000&i=gh&m=ci)

*Created by Jose Soto via Bugsnag*

**Comment by mattstauffer** [comment]
We're getting rid of Joind.in so dropping this.
