### ISSUE TITLE
GitHub icon on login page is borked

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/symposium#274]
![qwerqwerasdfa](https://user-images.githubusercontent.com/151829/63623947-038a3b80-c5c9-11e9-9f24-7183485ace5c.gif)

**Comment by tomdiggle** [comment]
I'm taking a look at this issue, because only login with GitHub is supported, would it make sense to replace the current 'auth-icons.png' file with an image of only the GitHub icon? I'd also update the CSS to use tailwind.

**Comment by mattstauffer** [comment]
@tomdiggle Yah, I think that makes sense :)
