### ISSUE TITLE
Login and signup errors are still being misdirected

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/symposium#275]
There are four places for potential errors to display: the sign in box on the home page, the sign up box on the home page, and the sign up and sign in pages. Almost all of the errors on these pages are either not showing, or not showing in the right spot. Let's fix.

https://stefanbauer.me/tips-and-tricks/multiple-forms-with-same-input-names-on-one-page

**Comment by josecanhelp** [comment]
@mattstauffer can we mark this issue resolved since we merged #276 ?

**Comment by mattstauffer** [comment]
Yessir!
