### ISSUE TITLE
Login no longer works

### ISSUE THREAD

**Issue by afilina** [tightenco/symposium#283]
I went to login using my credentials (not GitHub) and got a "419 | Page Expired." Pronto is also unable to fetch my talks, possibly for the same reason. I have 2 days left to submit to a conference and all my talks are in here.

**Comment by mattstauffer** [comment]
@afilina Taking a look at it now :)

**Comment by mattstauffer** [comment]
@afilina Login with and without github auth works fine for me. Can you try hard refreshing the home page then trying to log in again? usually the Page Expired happens when you've had a page open too long, and then try to submit; the CSRF token will have expired at that point.

**Comment by afilina** [comment]
That solved it, thanks. I haven't used it in almost a year, so no chance of CSRF being the issue.
