### ISSUE TITLE
Add some sort of reference of <3 to @mfrost503 & Dossier

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/symposium#30]

**Comment by mattstauffer** [comment]
:heart:

**Comment by mfrost503** [comment]
I'm @mfrost503 ;)

**Comment by mattstauffer** [comment]
Ha! Ok. Well some random other m frost is going to get a notification and
be very confused. :)

**Comment by mattstauffer** [comment]
This issue was moved to tightenco/symposium#30
