### ISSUE TITLE
Integration with OpenCFP

### ISSUE THREAD

**Issue by mdwheele** [tightenco/symposium#33]
OpenCFP is currently working on getting an API together to support use-cases like this system. I would consider the current status of development on that to be pre-draft (still fleshing ideas out).

However, I'd like to drop an issue here to see if there is interest in adding a "submit talks to conference" feature here whereby a prospective speaker could (minimally) push talks to a particular OpenCFP instance OR (ideally) complete the entire registration process in addition to submitting talks; achieving ultimate convenience for a speaker by reducing submission to pretty much a "one-click process".

I'm helping out over there because it's an awesome project and so is this and am interested in getting your thoughts here and helping with an implementation.

```gherkin
In order to reduce the amount of work required to visit each conference site and submit talks
As a prospective conference speaker
I want to be able to submit selected talks to a conference

Background:
  Given I have authenticated to SaveMyProposals
    And I have a version of a talk in SaveMyProposals I want to submit to conference CFPs

Scenario: Conference site has an mechanism to allow talks to be added externally
  Given I am reviewing conferences that have a CFP and the CFP has not ended
  When I choose to submit my talk(s) to the conference
  Then the talks are submitted using the appropriate appropriate mechanism for submission

Scenario: Conference site does not have a mechanism for adding talks from an external service
  Given I am reviewing conferences that have a CFP and the CFP has not ended
  When I choose to submit my talk(s) to the conference
  Then I am informed that the remote conference site does not support an external talk publishing option
    And I am directed to the CFP landing page for that conference

...
```

There are more scenarios to add to this, but I hope this is enough to start a conversation! Thanks @mattstauffer!

**Comment by mdwheele** [comment]
In addition, if there are reasonable ways to integrate this application with other types of CFP software, I am totally down to help write adapters for that as well.

**Comment by mattstauffer** [comment]
Absolutely! This is a sub-item of #29. Really good stuff @mdwheele--keep me updated as you guys develop it in OpenCFP; I think that's definitely the place to start.

**Comment by mdwheele** [comment]
Awesome, I'll send updates here. Sorry I missed the previous issue for some reason, haha.

**Comment by mattstauffer** [comment]
@mdwheele Just want to check in. My life has finally freed up to the point where I could collaborate on something like this. Let me know if you guys want to chat on that.

**Comment by mdwheele** [comment]
Definitely interested. I'm planning to work on this as part of the hackathon at #phptek so getting thoughts together beforehand would be good. I'll drop ideas when I'm back at desk.

**Comment by mdwheele** [comment]
@mattstauffer! I've submitted a documentation PR at https://github.com/opencfp/opencfp/pull/195. I'm about 70% done with the implementation and am putting this out there to get some feedback before a first iteration is cut. The goal is to get something functional ready before next week so that we can make any final adjustments as part of the hack-a-thon festivities at #phptek. Very interested in your thoughts on "how usable does this seem", "things you wish were there", etc.

Also, I am very interested in helping bridge Symposium over this API when we get it in place and am already planning on implementing a client that implements a lot of what I talk about in the docs. This should make integration a breeze, hopefully.

**Comment by mdwheele** [comment]
@mattstauffer Implementation PR for this has been submitted and we will be reviewing at the conference over the next couple of days. Being that things got a little further along quicker than I expected, I'm likely going to work on an example app that consumes the API. If you have time to enumerate the specific use-cases you're interested in, I'll go ahead and get us a client package for the API together as part of that example app.

If I had more time and organization skills, would have been badass for Symposium to be that "example app" haha.

**Comment by mattstauffer** [comment]
@mdwheele ha, we can be your first consumer for sure. FYI, all we care about at the moment is the ability to authenticate and then to submit talks. I presume we'd bet back an ID and then be able to read and update the talk description--or delete the proposal--with that. I'll try to write something more soon. 

My biggest curiosity is about how we are going to map our fields to each conferences fields. Is that something you've thought about? I wonder if that means we need an endpoint for "get me all fields on this CFP" so they can map them?

**Comment by adamwathan** [comment]
I think all OpenCFP conferences use the same submission format no? Definitely going to be very hard to build intelligence to handle different formats automatically if they are customizable :/

**Comment by mattstauffer** [comment]
Oh I dunno why I thought they were customizable. That would help :)

**Comment by mdwheele** [comment]
Hehe. So yeah, they are customizable to an extent which would include thinks like different talk categories, in the best case. In the worst case, they add all manner of custom attributes that must be attached. 

So two things:

1. Personally, I'd prefer to see these types of customization use cases baked into the product rather than having folks clone and make one-off tweaks. With this type of thing on the table, it is extremely difficult to build a reliable API. 
2. I would advise on standardizing an acceptable error response in our API to help better inform on broken validation rules etc. That said, I've thought about it quite a bit and any scenario where devs can make tweaks deviating away from accepted api is going to make things difficult. 

There are a NUMBER of technical solutions to this. However, I want to approach it making sure we aren't just putting out fires left and right. I think my preferred direction would be two-fold:

1. Provide end points for inspecting resource schema at some level. 
2. Standardize communication protocols such that conference specific rules are still allowed, but must be piped out through the API according to that protocol. 

Then you have the problem of making sure folks are running latest updates on OCFP! :)

It might be best to really dive deep on this as part of an integration collab and really try to root out all these cases the best we can rather than waiting for each conference to do so in the wild.

**Comment by mdwheele** [comment]
Adam's right though. I don't think you really GET to build intelligence for this sort of thing. I think it will come down to giving users of OCFP a framework to build in such that any customizations they want to make are expected and don't cause arbitrary deviance a away from an effort to build communicable protocols through a JSON API.

**Comment by mdwheele** [comment]
Last thing, I promise! No matter which way this falls, I do think it's important to shield consumers of the API from this kind of crap. This justifies, even more, necessity for a client package abstracting access to the API. Then you don't really have to make sense of so much or take on that cognitive load. We simply need to have discussion about types of things that can go wrong, go right; and start there. 

Lastly, through cursory examination, it seems that most of the tweaks folks make are to the static content pages in order to customize more of the marketing info. It seems rare that someone makes fundamental changes to things like account creation and talk submission and management. So this may not even be that big of a deal to manage. 

Loooooong term, I personally would like to see OpenCFP continue to split such that the core product is just the domain of CFP to be pulled in by any project as an implementation of the CFP process. Think that if you could do that now, we wouldn't be talking about an API for managing distribution of data, we would be solving the next problem! :)

**Comment by mattstauffer** [comment]
@mdwheele Good. I'm really happy. I had been attempting to plan around a really flexible system and it hurt my brain. This is so much better. And I totally hear you about your plans for OpenCFP.
