### ISSUE TITLE
Email validation from hell...

### ISSUE THREAD

**Issue by assertchris** [tightenco/symposium#42]
![screen shot 2015-03-17 at 3 27 40 pm](https://cloud.githubusercontent.com/assets/200609/6680302/321623cc-ccba-11e4-8e19-e24054a05a16.png)

...using the email "cgpitt@gmail.com"

**Comment by mattstauffer** [comment]
@assertchris WTF, yet another thing I didn't get notified about. Sorry! Will check

**Comment by mattstauffer** [comment]
@assertchris Can't reproduce this. Is it still happening?

**Comment by mattstauffer** [comment]
Closing because can't reproduce.
