### ISSUE TITLE
The concept of talk "versions" is confusing for people who don't want it

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/symposium#48]
It'd be better to hide all "version" talk until someone hit a button that said they want to version this talk or something.

**Comment by adamwathan** [comment]
I wonder if the simplest approach is to remove them altogether, and anyone who wants to keep 2 versions of a talk can just create two talks? As far as I can figure they wouldn't share that much right? Different abstracts, different slides, different notes, etc. I think the experience cost of supporting them isn't worth it since it's a pretty limited use case.

**Comment by mattstauffer** [comment]
Yah. That is absolutely worth considering. 

Sent from Outlook




On Fri, May 8, 2015 at 3:25 AM -0700, "Adam Wathan" <notifications@github.com> wrote:












I wonder if the simplest approach is to remove them altogether, and anyone who wants to keep 2 versions of a talk can just create two talks? As far as I can figure they wouldn't share that much right? Different abstracts, different slides, different notes, etc. I think the experience cost of supporting them isn't worth it since it's a pretty limited use case.

**Comment by mattstauffer** [comment]
I've been thinking about it for a while... versions offer a tiny bit of convenience, but the actual shared data between two versions is almost nothing.

And it adds a *ton* of code *and* user onboarding complexity.

I put out a request for feedback but if we don't hear back in the next day, I'll get started on dumping versions (and writing a migration script for anyone with live data that uses versions).

**Comment by mattstauffer** [comment]
https://twitter.com/assertchris/status/600404722311299073

@assertchris: "@stauffermatt think type is more valuable than version nickname. Removing versions will make all the things simple! :)"

**Comment by coderabbi** [comment]
I may be the minority here, but for me the 'version' is of the abstract, not the talk. The talk is the same, the question is which CfP Submissions (abstracts) got traction for that talk...

[[selfie-placeholder-0]]

[[selfie-placeholder-0]]

**Comment by adamwathan** [comment]
We got you covered on that either way :)



—
Adam

**Comment by mattstauffer** [comment]
@coderabbi I think that's solved more by revisions. :) Since a revision is linked to a submission.. Revision is more about history (e.g. "I submitted this revision to PHP Tek and this revision to these three conferences and I got into Tek but not the others")

**Comment by mattstauffer** [comment]
haha, like @adamwathan--we have that covered *sans* versions

**Comment by coderabbi** [comment]
Yep, that would work.

**Comment by mattstauffer** [comment]
OK, it has been decided. :) Thanks for the feedback!
