### ISSUE TITLE
Conference website URL and internal URL are colliding on the same attribute

### ISSUE THREAD

**Issue by adamwathan** [tightenco/symposium#72]
[This commit](https://github.com/tightenco/symposium/commit/b2a282e51425e1987bc968b3e39e0650cfa0f8de#diff-aa770d59320dd85fab1d88926b73a668R123) added a mutator that overrides the pre-existing `url` attribute to return an internal link.

We need to rename one of them. I recommend renaming the old `url` attribute to `external_url` and renaming the column in the database. Will require a manual audit of the codebase to figure out which calls need to be replaced.

**Comment by mattstauffer** [comment]
WHAT KIND OF A-HOLE WOULD DO THAT
