### ISSUE TITLE
[Proposal] - Allow tagging conferences

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/symposium#86]
I was just thinking a view like this might be well served by some form of categorization or tagging:
https://gist.github.com/DragonBe/51002bd40a6fa99a5123

E.g. `javascript`, `php`, `design`, `frontend`, etc.

**Comment by adamwathan** [comment]
Why?

:blush:

**Comment by mattstauffer** [comment]
lol
#annoyingquestions

Because, the more conferences we have, the more important it will be to surface the particular sort of conference people will be interested in.

Additionally, the excitement of seeing "Here's a list of all php conferences!" will be solveable, not through a ton of work by manually curating a gist, but just pasting a search term. That means it's providing benefit to our users--here are a bunch of conferences to see that serve your interests as an attendee, or more on-point, here are a bunch of conferences that you might want to apply to as a speaker. And it's also providing a hook to external folks--hey, Symposium is the place you think about when you want to think about conferences.

No, we don't want to dilute our product by focusing too much on being a conference-listing site, but I like the idea that there is a feature that might fit an internal need--"there are too many conferences in the list and I'd like to filter it down to conferences about PHP"--that also serves an external need that also has an advertising function--"I want to know what the upcoming PHP conferences are for attendance/application purposes."

**Comment by adamwathan** [comment]
> Because, the more conferences we have, the more important it will be to surface the particular sort of conference people will be interested in.

Why? Still haven't identified the actual problem :blush: Let's identify the actual _situation_ where this is useful. I'm 90% sure it's a good feature but it's important to frame the feature in the context of a real world situation it solves if we want to do a good job.

I have ideas about what the situations and problems are but I wanna make you go first :smile: 

And a relevant Ryan Singer reference for good measure, from the [Vital Elements of the Design Process](http://feltpresence.com/articles/20):

> Sometimes people think they have defined the problem, but they really just defined a feature. Like “users want file versioning.” It’s important to understand that a feature is not a situation. You can dig into a situation to learn what is valuable and what is not according to the goal. Digging into a feature definition doesn’t do that. It has no origin and no goal. Analyzing a feature definition leads you to play out all the things a person might value from the feature instead of learning what they actually value.
>
> Suppose a team is building a “file versions” feature. Two situations define the value differently and lead to different designs.
>
> In one situation, a person catches an embarrassing mistake in a proposal and wants to know who to blame. In order to do this, they need to see information about intermediate versions. They value the product telling them who made what changes and when.
>
> On the other hand, consider a situation where they want to send the latest version of the proposal to the client. They don’t care how it got to its current state. They just want to send the correct file. In this case intermediate versions have no value. The user just wants to know where the latest version is.
>
> Deciding which situation you are designing for focuses the problem. Focusing the problem focuses the team. When the team knows where the value is, they stop speculating about all possible cases and they get down to business. It’s easier to make decisions about what’s in and what’s out. This leads to a clearer criteria for which patterns are appropriate, in turn leading to a clearer product concept.

**Comment by mattstauffer** [comment]
Man, between you and my two-year-old I'll get tired of the word "Why" very soon. ;)

> Because, the more conferences we have, the more important it will be to surface the particular sort of conference people will be interested in.

When I want to find conferences I might be interested in, because I want to either attend (less likely because it's not our primary purpose but still possible) or apply (more likely because it's the purpose), and I want to attend and apply to conferences that are actually interesting to me--whether that metric is based on location or date or language or whatever--I need to be able to find the conferences that are interesting to me quickly. The larger the database of conferences, the harder it is to find what you want. In this context I'm talking about people who come to our app looking for conferences to apply to.
