### ISSUE TITLE
Missing Revisions

### ISSUE THREAD

**Issue by coderabbi** [tightenco/symposium#87]

**Comment by coderabbi** [comment]
All revisions return the Laravel 500 page. :-(

**Comment by mattstauffer** [comment]
I think it's actually just supposed to throw a "this page hasn't been programmed yet" error :) thanks for the reminder!!
Sent from Outlook




On Fri, Jun 5, 2015 at 3:08 PM -0700, "Yitzchok Willroth" <notifications@github.com> wrote:












All revisions return the Laravel 500 page. :-(
