### ISSUE TITLE
[Proposal] - Provide public speaker pages

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/symposium#94]
My thought:
Give each user an optional public page that shows their bio, headshot, talks they've given in the past, a "contact me" button, and maybe a Namez (http://namez.com/profiles/133-tom-ehrhardt/records/6837-philipp-lahm) link for pronunciation

**Comment by kayladnls** [comment]
+1 +1 +1 I was coming to find you while we're both in AMS to propose this. I've talked to a number of organizers and they thing it would be helpful. I'd love to help you add it.

**Comment by mattstauffer** [comment]
Working on it here: https://github.com/tightenco/symposium/pull/106

**Comment by kayladnls** [comment]
#106 is merged so you could probably close this, yeah?

**Comment by mattstauffer** [comment]
Yep! Thanks!
