### ISSUE TITLE
Conference Filters are confusing

### ISSUE THREAD

**Issue by rdohms** [tightenco/symposium#98]
So there are two filters that i confuse: "CFP is Open" and "Unclosed CFP" .. they sound like the same thing but "CFP is Open" actually lists CFP's that have closed.

Also `http://symposiumapp.com/conferences?filter=unclosed_cfp&sort=closing_next` does not sort ASC from closes end date, rather DESC it seems.

**Comment by mattstauffer** [comment]
Thanks @rdohms! Extracting the second half to a separate issue.
